### ISSUE TITLE
roadmapping

### ISSUE THREAD

**Issue by serapath** [playproject-io/blog#2]
## `@todo`
* [ ] make blog concept
* [ ] create article with play embedded and version of workshop-app with play + ethereum/play colors and logo and cross publish on medium and social media
* [ ] [`blog#1` - technical writing](https://github.com/playpoject-io/blog/issues/1)
* [ ] [`blog#3` - blog series about smartcontract.code](https://github.com/playpoject-io/blog/issues/3)

---
