### ISSUE TITLE
blog series about smartcontract.codes

### ISSUE THREAD

**Issue by serapath** [playproject-io/blog#3]
## `@todo`
* [ ] explain through articles
    * [ ] which problem its solving (verified contracts)
    * [ ] how to use smartcontract.codes
    * [ ] objectives and vision for smartcontract.codes
    * [ ] add links to documentation

---
